ALTER TABLE trips.trip_request
  ADD COLUMN start_code                     TEXT,
  ADD COLUMN start_code_failed_attempts     SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN start_code_blocked_at          TIMESTAMP(3),
  ADD COLUMN start_code_exempt              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN started_at                     TIMESTAMP(3),
  ADD COLUMN pickup_distance_at_assignment_m INTEGER;

UPDATE trips.trip_request
   SET start_code_exempt = true
 WHERE status IN ('assigned', 'driver_en_route');

CREATE FUNCTION trips.new_start_code() RETURNS text
LANGUAGE sql
VOLATILE
SECURITY INVOKER
SET search_path = pg_catalog, pg_temp
AS $$
  SELECT lpad((((get_byte(b, 0)::bigint << 24) | (get_byte(b, 1)::bigint << 16)
               | (get_byte(b, 2)::bigint << 8) | get_byte(b, 3)::bigint) % 10000)::text, 4, '0')
    FROM (SELECT uuid_send(gen_random_uuid()) AS b) s
$$;

CREATE FUNCTION trips.trip_request_start_code_guard() RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, trips, pg_temp
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.start_code_failed_attempts := 0;
    NEW.start_code_blocked_at := NULL;
    NEW.start_code_exempt := false;
    NEW.start_code := CASE WHEN NEW.status IN ('assigned', 'driver_en_route')
                           THEN trips.new_start_code() END;
    RETURN NEW;
  END IF;

  IF OLD.start_code_failed_attempts > 0
     AND (NEW.status = 'pending_assignment'
          OR (NEW.status IN ('assigned', 'driver_en_route')
              AND OLD.status NOT IN ('assigned', 'driver_en_route'))) THEN
    RAISE EXCEPTION 'ADR-033: a trip with failed start attempts cannot be reopened' USING ERRCODE = 'check_violation';
  END IF;

  IF NEW.status IN ('assigned', 'driver_en_route')
     AND OLD.status NOT IN ('assigned', 'driver_en_route') THEN
    NEW.start_code := trips.new_start_code();
    NEW.start_code_failed_attempts := 0;
    NEW.start_code_blocked_at := NULL;
    NEW.start_code_exempt := false;
    RETURN NEW;
  END IF;

  IF NEW.status = 'pending_assignment' THEN
    NEW.start_code := NULL;
    NEW.start_code_failed_attempts := 0;
    NEW.start_code_blocked_at := NULL;
    NEW.start_code_exempt := false;
    RETURN NEW;
  END IF;

  IF NEW.start_code IS NOT NULL AND NEW.start_code IS DISTINCT FROM OLD.start_code THEN
    RAISE EXCEPTION 'ADR-033: start_code is generated by the database' USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.start_code_failed_attempts < OLD.start_code_failed_attempts
     OR (OLD.start_code_blocked_at IS NOT NULL AND NEW.start_code_blocked_at IS DISTINCT FROM OLD.start_code_blocked_at)
     OR NEW.start_code_exempt IS DISTINCT FROM OLD.start_code_exempt THEN
    RAISE EXCEPTION 'ADR-033: start code attempts, block and exemption cannot be undone' USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.status NOT IN ('assigned', 'driver_en_route') THEN
    NEW.start_code := NULL;
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER trip_request_start_code
  BEFORE INSERT OR UPDATE OF status, start_code, start_code_failed_attempts, start_code_blocked_at, start_code_exempt
  ON trips.trip_request
  FOR EACH ROW EXECUTE FUNCTION trips.trip_request_start_code_guard();

ALTER TABLE trips.trip_request
  ADD CONSTRAINT trip_request_start_code_format   CHECK (start_code IS NULL OR start_code ~ '^[0-9]{4}$'),
  ADD CONSTRAINT trip_request_start_code_attempts CHECK (start_code_failed_attempts BETWEEN 0 AND 5),
  ADD CONSTRAINT trip_request_start_code_blocked  CHECK ((start_code_blocked_at IS NOT NULL) = (start_code_failed_attempts = 5)),
  ADD CONSTRAINT trip_request_start_code_window   CHECK (start_code IS NULL
                                                         OR (status IN ('assigned', 'driver_en_route') AND start_code_blocked_at IS NULL)),
  ADD CONSTRAINT trip_request_start_code_present  CHECK (status NOT IN ('assigned', 'driver_en_route')
                                                         OR start_code IS NOT NULL OR start_code_exempt
                                                         OR start_code_blocked_at IS NOT NULL);
